services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  wiremock:
    image: wiremock/wiremock:3.5.2
    container_name: wiremock
    ports:
      - "8089:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command: --verbose --global-response-templating
    restart: unless-stopped

volumes:
  redis_data: